#!/usr/bin/env python3
from pathlib import Path


def replace(path: str, old: str, new: str, expected: int = 1) -> None:
    file = Path(path)
    value = file.read_text(encoding="utf-8")
    actual = value.count(old)
    if actual != expected:
        raise SystemExit(f"{path}: expected {expected} matches, found {actual}: {old[:120]!r}")
    file.write_text(value.replace(old, new, expected), encoding="utf-8")


def replace_between(path: str, start: str, end: str, replacement: str) -> None:
    file = Path(path)
    value = file.read_text(encoding="utf-8")
    first = value.find(start)
    if first < 0:
        raise SystemExit(f"{path}: missing start marker {start!r}")
    second = value.find(end, first)
    if second < 0:
        raise SystemExit(f"{path}: missing end marker {end!r}")
    if value.find(start, first + 1) >= 0:
        raise SystemExit(f"{path}: duplicate start marker {start!r}")
    file.write_text(value[:first] + replacement + value[second:], encoding="utf-8")


# Provider-neutral storage intent and recovery contract.
replace(
    "crates/heptabao-storage-api/src/lib.rs",
    "#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub struct CommitReceipt {\n"
    "    pub previous: Option<Generation>,\n"
    "    pub committed: Generation,\n"
    "    pub digest: StateDigest,\n"
    "}\n\n",
    "#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub struct CommitReceipt {\n"
    "    pub previous: Option<Generation>,\n"
    "    pub committed: Generation,\n"
    "    pub digest: StateDigest,\n"
    "}\n\n"
    "#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n"
    "pub struct CommitIntent {\n"
    "    previous: Option<Generation>,\n"
    "    committed: Generation,\n"
    "    digest: StateDigest,\n"
    "}\n\n"
    "impl CommitIntent {\n"
    "    pub fn new(\n"
    "        previous: Option<Generation>,\n"
    "        committed: Generation,\n"
    "        digest: StateDigest,\n"
    "    ) -> Result<Self, StorageContractError> {\n"
    "        let expected = match previous {\n"
    "            Some(value) => value.checked_next()?,\n"
    "            None => Generation::INITIAL,\n"
    "        };\n"
    "        if committed != expected {\n"
    "            return Err(StorageContractError::InvalidCommitIntent);\n"
    "        }\n"
    "        Ok(Self {\n"
    "            previous,\n"
    "            committed,\n"
    "            digest,\n"
    "        })\n"
    "    }\n\n"
    "    pub const fn previous(self) -> Option<Generation> {\n"
    "        self.previous\n"
    "    }\n\n"
    "    pub const fn committed(self) -> Generation {\n"
    "        self.committed\n"
    "    }\n\n"
    "    pub const fn digest(self) -> StateDigest {\n"
    "        self.digest\n"
    "    }\n\n"
    "    pub const fn receipt(self) -> CommitReceipt {\n"
    "        CommitReceipt {\n"
    "            previous: self.previous,\n"
    "            committed: self.committed,\n"
    "            digest: self.digest,\n"
    "        }\n"
    "    }\n"
    "}\n\n"
    "#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n"
    "pub enum CommitRecovery {\n"
    "    Committed(CommitReceipt),\n"
    "    NotCommitted,\n"
    "    Conflict {\n"
    "        actual: Option<(Generation, StateDigest)>,\n"
    "    },\n"
    "}\n\n",
)
replace(
    "crates/heptabao-storage-api/src/lib.rs",
    "    fn load_current(&self) -> Result<Option<GenerationSnapshot>, Self::Error>;\n\n"
    "    fn commit(\n",
    "    fn load_current(&self) -> Result<Option<GenerationSnapshot>, Self::Error>;\n\n"
    "    /// Computes the exact generation and digest that a subsequent commit\n"
    "    /// must publish, without mutating authoritative storage.\n"
    "    fn prepare_commit(\n"
    "        &self,\n"
    "        expected_current: Option<Generation>,\n"
    "        candidate: &OpaqueState,\n"
    "    ) -> Result<CommitIntent, Self::Error>;\n\n"
    "    /// Re-reads authoritative provider state and classifies an interrupted\n"
    "    /// prepared commit. Implementations may complete publication only when\n"
    "    /// the persisted candidate exactly matches the supplied intent.\n"
    "    fn recover_commit(\n"
    "        &mut self,\n"
    "        intent: CommitIntent,\n"
    "    ) -> Result<CommitRecovery, Self::Error>;\n\n"
    "    fn commit(\n",
)
replace(
    "crates/heptabao-storage-api/src/lib.rs",
    "    InvalidOpaqueState,\n}\n",
    "    InvalidOpaqueState,\n    InvalidCommitIntent,\n}\n",
)
replace(
    "crates/heptabao-storage-api/src/lib.rs",
    "            Self::InvalidOpaqueState => \"opaque state is empty or exceeds the bounded size\",\n",
    "            Self::InvalidOpaqueState => \"opaque state is empty or exceeds the bounded size\",\n"
    "            Self::InvalidCommitIntent => {\n"
    "                \"commit intent generation is not the exact successor of its previous generation\"\n"
    "            }\n",
)
replace(
    "crates/heptabao-storage-api/src/lib.rs",
    "    #[test]\n    fn zero_digest_is_rejected() {\n",
    "    #[test]\n"
    "    fn commit_intent_requires_exact_generation_successor() {\n"
    "        let digest = StateDigest::new([7; 32]);\n"
    "        assert!(digest.is_ok());\n"
    "        if let Ok(digest) = digest {\n"
    "            assert!(CommitIntent::new(None, Generation::INITIAL, digest).is_ok());\n"
    "            assert_eq!(\n"
    "                CommitIntent::new(None, Generation::new(2).unwrap_or(Generation::INITIAL), digest),\n"
    "                Err(StorageContractError::InvalidCommitIntent)\n"
    "            );\n"
    "            let second = Generation::INITIAL.checked_next();\n"
    "            assert!(second.is_ok());\n"
    "            if let Ok(second) = second {\n"
    "                assert!(CommitIntent::new(Some(Generation::INITIAL), second, digest).is_ok());\n"
    "            }\n"
    "        }\n"
    "    }\n\n"
    "    #[test]\n    fn zero_digest_is_rejected() {\n",
)

# Durable core prepares sealed candidate and exact storage intent before dispatch.
replace(
    "crates/heptabao-durable-core/src/lib.rs",
    "    CommitReceipt, DurableGenerationStore, Generation, OpaqueState, StateDigest,\n"
    "    StorageContractError,\n",
    "    CommitIntent, CommitReceipt, CommitRecovery, DurableGenerationStore, Generation, OpaqueState,\n"
    "    StateDigest, StorageContractError,\n",
)
replace(
    "crates/heptabao-durable-core/src/lib.rs",
    "impl<S, B> DurableStateEngine<S, B>\nwhere\n    S: DurableGenerationStore,\n    B: BarrierProvider,\n{\n",
    "pub struct PreparedDurableMutation {\n"
    "    intent: CommitIntent,\n"
    "    candidate: OpaqueState,\n"
    "}\n\n"
    "impl PreparedDurableMutation {\n"
    "    pub const fn intent(&self) -> CommitIntent {\n"
    "        self.intent\n"
    "    }\n"
    "}\n\n"
    "impl fmt::Debug for PreparedDurableMutation {\n"
    "    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {\n"
    "        formatter\n"
    "            .debug_struct(\"PreparedDurableMutation\")\n"
    "            .field(\"intent\", &self.intent)\n"
    "            .field(\"candidate_bytes\", &self.candidate.len())\n"
    "            .field(\"candidate\", &\"[SEALED_REDACTED]\")\n"
    "            .finish()\n"
    "    }\n"
    "}\n\n"
    "impl<S, B> DurableStateEngine<S, B>\nwhere\n    S: DurableGenerationStore,\n    B: BarrierProvider,\n{\n",
)
replace_between(
    "crates/heptabao-durable-core/src/lib.rs",
    "    pub fn persist(\n",
    "    pub fn load_current(\n",
    "    pub fn prepare_persist(\n"
    "        &self,\n"
    "        expected_current: Option<Generation>,\n"
    "        plaintext: SecretState,\n"
    "        caller_associated_data: Vec<u8>,\n"
    "    ) -> Result<PreparedDurableMutation, DurableCoreError<S::Error, B::Error>> {\n"
    "        let actual = self.store.current_generation();\n"
    "        if expected_current != actual {\n"
    "            return Err(DurableCoreError::GenerationConflict {\n"
    "                expected: expected_current,\n"
    "                actual,\n"
    "            });\n"
    "        }\n"
    "        let generation = match actual {\n"
    "            Some(value) => value\n"
    "                .checked_next()\n"
    "                .map_err(DurableCoreError::StorageContract)?,\n"
    "            None => Generation::INITIAL,\n"
    "        };\n"
    "        let key_epoch = self\n"
    "            .barrier\n"
    "            .active_key_epoch()\n"
    "            .map_err(DurableCoreError::Barrier)?;\n"
    "        let context = BarrierContext::new(\n"
    "            self.store.domain().clone(),\n"
    "            generation,\n"
    "            key_epoch,\n"
    "            BarrierPurpose::AuthoritativeState,\n"
    "            caller_associated_data,\n"
    "        )\n"
    "        .map_err(DurableCoreError::BarrierContract)?;\n"
    "        let envelope = self\n"
    "            .barrier\n"
    "            .seal(&context, plaintext)\n"
    "            .map_err(DurableCoreError::Barrier)?;\n"
    "        if envelope.key_epoch() != key_epoch {\n"
    "            return Err(DurableCoreError::BarrierEpochMismatch {\n"
    "                requested: key_epoch,\n"
    "                returned: envelope.key_epoch(),\n"
    "            });\n"
    "        }\n"
    "        let encoded = envelope\n"
    "            .encode()\n"
    "            .map_err(DurableCoreError::BarrierContract)?;\n"
    "        let candidate = OpaqueState::new(encoded).map_err(DurableCoreError::StorageContract)?;\n"
    "        let intent = self\n"
    "            .store\n"
    "            .prepare_commit(expected_current, &candidate)\n"
    "            .map_err(DurableCoreError::Storage)?;\n"
    "        if intent.previous() != expected_current || intent.committed() != generation {\n"
    "            return Err(DurableCoreError::CommitIntentMismatch);\n"
    "        }\n"
    "        Ok(PreparedDurableMutation { intent, candidate })\n"
    "    }\n\n"
    "    pub fn commit_prepared(\n"
    "        &mut self,\n"
    "        prepared: PreparedDurableMutation,\n"
    "    ) -> Result<CommitReceipt, DurableCoreError<S::Error, B::Error>> {\n"
    "        let receipt = self\n"
    "            .store\n"
    "            .commit(prepared.intent.previous(), prepared.candidate)\n"
    "            .map_err(DurableCoreError::Storage)?;\n"
    "        if receipt != prepared.intent.receipt() {\n"
    "            return Err(DurableCoreError::CommitReceiptMismatch);\n"
    "        }\n"
    "        Ok(receipt)\n"
    "    }\n\n"
    "    pub fn recover_commit(\n"
    "        &mut self,\n"
    "        intent: CommitIntent,\n"
    "    ) -> Result<CommitRecovery, DurableCoreError<S::Error, B::Error>> {\n"
    "        self.store\n"
    "            .recover_commit(intent)\n"
    "            .map_err(DurableCoreError::Storage)\n"
    "    }\n\n"
    "    pub fn persist(\n"
    "        &mut self,\n"
    "        expected_current: Option<Generation>,\n"
    "        plaintext: SecretState,\n"
    "        caller_associated_data: Vec<u8>,\n"
    "    ) -> Result<CommitReceipt, DurableCoreError<S::Error, B::Error>> {\n"
    "        let prepared =\n"
    "            self.prepare_persist(expected_current, plaintext, caller_associated_data)?;\n"
    "        self.commit_prepared(prepared)\n"
    "    }\n\n",
)
replace(
    "crates/heptabao-durable-core/src/lib.rs",
    "    CommitReceiptMismatch,\n}\n",
    "    CommitIntentMismatch,\n    CommitReceiptMismatch,\n}\n",
)
replace(
    "crates/heptabao-durable-core/src/lib.rs",
    "            Self::CommitReceiptMismatch => {\n"
    "                formatter.write_str(\"durable store returned a mismatched commit receipt\")\n"
    "            }\n",
    "            Self::CommitIntentMismatch => {\n"
    "                formatter.write_str(\"durable store returned a mismatched commit intent\")\n"
    "            }\n"
    "            Self::CommitReceiptMismatch => {\n"
    "                formatter.write_str(\"durable store returned a mismatched commit receipt\")\n"
    "            }\n",
)
replace(
    "crates/heptabao-durable-core/src/lib.rs",
    "        fn commit(\n"
    "            &mut self,\n"
    "            expected_current: Option<Generation>,\n"
    "            candidate: OpaqueState,\n"
    "        ) -> Result<CommitReceipt, Self::Error> {\n",
    "        fn prepare_commit(\n"
    "            &self,\n"
    "            expected_current: Option<Generation>,\n"
    "            candidate: &OpaqueState,\n"
    "        ) -> Result<CommitIntent, Self::Error> {\n"
    "            if expected_current != self.current {\n"
    "                return Err(MemoryStoreError::Conflict);\n"
    "            }\n"
    "            let committed = match self.current {\n"
    "                Some(value) => value.checked_next().map_err(MemoryStoreError::Contract)?,\n"
    "                None => Generation::INITIAL,\n"
    "            };\n"
    "            let digest = test_digest(committed, candidate.as_bytes())?;\n"
    "            CommitIntent::new(expected_current, committed, digest)\n"
    "                .map_err(MemoryStoreError::Contract)\n"
    "        }\n\n"
    "        fn recover_commit(\n"
    "            &mut self,\n"
    "            intent: CommitIntent,\n"
    "        ) -> Result<CommitRecovery, Self::Error> {\n"
    "            match (self.current, self.digest) {\n"
    "                (Some(generation), Some(digest))\n"
    "                    if generation == intent.committed() && digest == intent.digest() =>\n"
    "                {\n"
    "                    Ok(CommitRecovery::Committed(intent.receipt()))\n"
    "                }\n"
    "                (generation, _) if generation == intent.previous() => {\n"
    "                    Ok(CommitRecovery::NotCommitted)\n"
    "                }\n"
    "                (Some(generation), Some(digest)) => Ok(CommitRecovery::Conflict {\n"
    "                    actual: Some((generation, digest)),\n"
    "                }),\n"
    "                _ => Ok(CommitRecovery::Conflict { actual: None }),\n"
    "            }\n"
    "        }\n\n"
    "        fn commit(\n"
    "            &mut self,\n"
    "            expected_current: Option<Generation>,\n"
    "            candidate: OpaqueState,\n"
    "        ) -> Result<CommitReceipt, Self::Error> {\n",
)
replace(
    "crates/heptabao-durable-core/src/lib.rs",
    "    #[test]\n    fn plaintext_is_sealed_before_storage_and_round_trips() {\n",
    "    #[test]\n"
    "    fn prepared_mutation_binds_target_before_authoritative_commit() {\n"
    "        let domain = domain();\n"
    "        if let Ok(domain) = domain {\n"
    "            let store = MemoryStore::new(domain);\n"
    "            let mut engine = DurableStateEngine::new(store, MockBarrier);\n"
    "            let secret = SecretState::new(b\"prepared-state\".to_vec());\n"
    "            assert!(secret.is_ok());\n"
    "            if let Ok(secret) = secret {\n"
    "                let prepared = engine.prepare_persist(None, secret, Vec::new());\n"
    "                assert!(prepared.is_ok());\n"
    "                if let Ok(prepared) = prepared {\n"
    "                    assert_eq!(prepared.intent().previous(), None);\n"
    "                    assert_eq!(prepared.intent().committed(), Generation::INITIAL);\n"
    "                    assert_eq!(engine.store().current_generation(), None);\n"
    "                    assert_eq!(\n"
    "                        engine.commit_prepared(prepared).map(|value| value.committed),\n"
    "                        Ok(Generation::INITIAL)\n"
    "                    );\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "    }\n\n"
    "    #[test]\n    fn plaintext_is_sealed_before_storage_and_round_trips() {\n",
)

# File provider computes exact intent and recovers stale CURRENT / exact orphan bundles.
replace(
    "crates/heptabao-single-node-store/src/lib.rs",
    "    CommitReceipt, DurableGenerationStore, Generation, GenerationSnapshot, IntegrityProvider,\n"
    "    OpaqueState, StateDigest, StorageContractError, StoreDomain, StoreOpenMode,\n",
    "    CommitIntent, CommitReceipt, CommitRecovery, DurableGenerationStore, Generation,\n"
    "    GenerationSnapshot, IntegrityProvider, OpaqueState, StateDigest, StorageContractError,\n"
    "    StoreDomain, StoreOpenMode,\n",
)
replace(
    "crates/heptabao-single-node-store/src/lib.rs",
    "    fn ensure_disk_matches_memory(&self) -> Result<(), FileStoreError<P::Error>> {\n",
    "    fn read_optional_current_record(\n"
    "        &self,\n"
    "    ) -> Result<Option<CurrentRecord>, FileStoreError<P::Error>> {\n"
    "        match fs::symlink_metadata(self.current_path()) {\n"
    "            Ok(_) => {\n"
    "                let bytes = read_regular_file(&self.current_path(), MAX_CONTROL_FILE_BYTES)?;\n"
    "                decode_current(&bytes)\n"
    "                    .map(Some)\n"
    "                    .map_err(|_| FileStoreError::CorruptState)\n"
    "            }\n"
    "            Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(None),\n"
    "            Err(error) => Err(FileStoreError::Io(error)),\n"
    "        }\n"
    "    }\n\n"
    "    fn regular_file_exists(\n"
    "        &self,\n"
    "        path: &Path,\n"
    "    ) -> Result<bool, FileStoreError<P::Error>> {\n"
    "        match fs::symlink_metadata(path) {\n"
    "            Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_file() => {\n"
    "                Err(FileStoreError::UnsafeFileType)\n"
    "            }\n"
    "            Ok(_) => Ok(true),\n"
    "            Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(false),\n"
    "            Err(error) => Err(FileStoreError::Io(error)),\n"
    "        }\n"
    "    }\n\n"
    "    fn publish_current_record(\n"
    "        &self,\n"
    "        record: CurrentRecord,\n"
    "    ) -> Result<(), FileStoreError<P::Error>> {\n"
    "        let mut bytes = encode_current(record);\n"
    "        let result = atomic_replace(&self.root, CURRENT_NAME, &bytes);\n"
    "        bytes.fill(0);\n"
    "        match result {\n"
    "            Ok(()) => Ok(()),\n"
    "            Err(error) if error.published => Err(FileStoreError::CommitOutcomeUnknown),\n"
    "            Err(error) => Err(FileStoreError::Io(error.source)),\n"
    "        }\n"
    "    }\n\n"
    "    fn ensure_disk_matches_memory(&self) -> Result<(), FileStoreError<P::Error>> {\n",
)
replace(
    "crates/heptabao-single-node-store/src/lib.rs",
    "    fn commit(\n"
    "        &mut self,\n"
    "        expected_current: Option<Generation>,\n"
    "        candidate: OpaqueState,\n"
    "    ) -> Result<CommitReceipt, Self::Error> {\n",
    "    fn prepare_commit(\n"
    "        &self,\n"
    "        expected_current: Option<Generation>,\n"
    "        candidate: &OpaqueState,\n"
    "    ) -> Result<CommitIntent, Self::Error> {\n"
    "        self.ensure_disk_matches_memory()?;\n"
    "        if expected_current != self.current {\n"
    "            return Err(FileStoreError::GenerationConflict {\n"
    "                expected: expected_current,\n"
    "                actual: self.current,\n"
    "            });\n"
    "        }\n"
    "        let committed = match self.current {\n"
    "            Some(value) => value.checked_next().map_err(FileStoreError::Contract)?,\n"
    "            None => Generation::INITIAL,\n"
    "        };\n"
    "        let digest = self\n"
    "            .integrity\n"
    "            .digest(&self.domain, committed, candidate.as_bytes())\n"
    "            .map_err(FileStoreError::IntegrityProvider)?;\n"
    "        CommitIntent::new(expected_current, committed, digest).map_err(FileStoreError::Contract)\n"
    "    }\n\n"
    "    fn recover_commit(\n"
    "        &mut self,\n"
    "        intent: CommitIntent,\n"
    "    ) -> Result<CommitRecovery, Self::Error> {\n"
    "        self.root.verify().map_err(map_directory_guard_error)?;\n"
    "        reject_unresolved_temporary_artifacts(self.root.access_path())?;\n"
    "        let marker_exists = self.regular_file_exists(&self.marker_path())?;\n"
    "        let disk_current = self.read_optional_current_record()?;\n"
    "        if intent.previous().is_some() {\n"
    "            if !marker_exists {\n"
    "                return Err(FileStoreError::MarkerMissing);\n"
    "            }\n"
    "            self.validate_marker()?;\n"
    "        } else if marker_exists {\n"
    "            self.validate_marker()?;\n"
    "            if disk_current.is_none() {\n"
    "                return Err(FileStoreError::CorruptState);\n"
    "            }\n"
    "        }\n\n"
    "        if let Some(record) = disk_current {\n"
    "            let bundle = self.read_and_verify_bundle(record.generation)?;\n"
    "            if bundle.digest != record.digest {\n"
    "                return Err(FileStoreError::CorruptState);\n"
    "            }\n"
    "        }\n\n"
    "        match disk_current {\n"
    "            Some(record) if record.generation == intent.committed() => {\n"
    "                if record.digest != intent.digest() {\n"
    "                    return Ok(CommitRecovery::Conflict {\n"
    "                        actual: Some((record.generation, record.digest)),\n"
    "                    });\n"
    "                }\n"
    "                if intent.previous().is_none() && !marker_exists {\n"
    "                    if self.publish_marker().is_err() {\n"
    "                        return Err(FileStoreError::CommitOutcomeUnknown);\n"
    "                    }\n"
    "                }\n"
    "                self.validate_marker()?;\n"
    "                self.current = Some(record.generation);\n"
    "                Ok(CommitRecovery::Committed(intent.receipt()))\n"
    "            }\n"
    "            Some(record) if Some(record.generation) == intent.previous() => {\n"
    "                if !self.regular_file_exists(&self.bundle_path(intent.committed()))? {\n"
    "                    self.current = Some(record.generation);\n"
    "                    return Ok(CommitRecovery::NotCommitted);\n"
    "                }\n"
    "                let bundle = self.read_and_verify_bundle(intent.committed())?;\n"
    "                if bundle.digest != intent.digest() {\n"
    "                    return Ok(CommitRecovery::Conflict {\n"
    "                        actual: Some((record.generation, record.digest)),\n"
    "                    });\n"
    "                }\n"
    "                self.publish_current_record(CurrentRecord {\n"
    "                    generation: intent.committed(),\n"
    "                    digest: intent.digest(),\n"
    "                })?;\n"
    "                let verified = self.read_current_record()?;\n"
    "                if verified.generation != intent.committed() || verified.digest != intent.digest() {\n"
    "                    return Err(FileStoreError::CommitOutcomeUnknown);\n"
    "                }\n"
    "                self.current = Some(intent.committed());\n"
    "                Ok(CommitRecovery::Committed(intent.receipt()))\n"
    "            }\n"
    "            None if intent.previous().is_none() => {\n"
    "                if !self.regular_file_exists(&self.bundle_path(intent.committed()))? {\n"
    "                    self.current = None;\n"
    "                    return Ok(CommitRecovery::NotCommitted);\n"
    "                }\n"
    "                let bundle = self.read_and_verify_bundle(intent.committed())?;\n"
    "                if bundle.digest != intent.digest() {\n"
    "                    return Ok(CommitRecovery::Conflict { actual: None });\n"
    "                }\n"
    "                self.publish_current_record(CurrentRecord {\n"
    "                    generation: intent.committed(),\n"
    "                    digest: intent.digest(),\n"
    "                })?;\n"
    "                if self.publish_marker().is_err() {\n"
    "                    return Err(FileStoreError::CommitOutcomeUnknown);\n"
    "                }\n"
    "                let verified = self.read_current_record()?;\n"
    "                self.validate_marker()?;\n"
    "                if verified.generation != intent.committed() || verified.digest != intent.digest() {\n"
    "                    return Err(FileStoreError::CommitOutcomeUnknown);\n"
    "                }\n"
    "                self.current = Some(intent.committed());\n"
    "                Ok(CommitRecovery::Committed(intent.receipt()))\n"
    "            }\n"
    "            Some(record) => Ok(CommitRecovery::Conflict {\n"
    "                actual: Some((record.generation, record.digest)),\n"
    "            }),\n"
    "            None => Ok(CommitRecovery::Conflict { actual: None }),\n"
    "        }\n"
    "    }\n\n"
    "    fn commit(\n"
    "        &mut self,\n"
    "        expected_current: Option<Generation>,\n"
    "        candidate: OpaqueState,\n"
    "    ) -> Result<CommitReceipt, Self::Error> {\n",
)
replace(
    "crates/heptabao-single-node-store/src/lib.rs",
    "    #[test]\n    fn compare_and_swap_rejects_stale_expected_generation() {\n",
    "    #[test]\n"
    "    fn authoritative_recovery_classifies_unwritten_and_published_intents() {\n"
    "        let temporary = TempDirectory::new();\n"
    "        let domain = domain();\n"
    "        let integrity = TestIntegrity::new();\n"
    "        if let (Ok(temporary), Ok(domain), Ok(integrity)) = (temporary, domain, integrity) {\n"
    "            let store = FileGenerationStore::create_new(&temporary.path, domain, integrity);\n"
    "            assert!(store.is_ok());\n"
    "            if let Ok(mut store) = store {\n"
    "                let candidate = OpaqueState::new(b\"recoverable-state\".to_vec());\n"
    "                assert!(candidate.is_ok());\n"
    "                if let Ok(candidate) = candidate {\n"
    "                    let intent = store.prepare_commit(None, &candidate);\n"
    "                    assert!(intent.is_ok());\n"
    "                    if let Ok(intent) = intent {\n"
    "                        assert_eq!(store.recover_commit(intent), Ok(CommitRecovery::NotCommitted));\n"
    "                        assert!(store.commit(None, candidate).is_ok());\n"
    "                        store.current = None;\n"
    "                        assert_eq!(\n"
    "                            store.recover_commit(intent),\n"
    "                            Ok(CommitRecovery::Committed(intent.receipt()))\n"
    "                        );\n"
    "                    }\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "    }\n\n"
    "    #[test]\n"
    "    fn exact_orphan_bundle_is_completed_only_for_matching_intent() {\n"
    "        let temporary = TempDirectory::new();\n"
    "        let domain = domain();\n"
    "        let integrity = TestIntegrity::new();\n"
    "        if let (Ok(temporary), Ok(domain), Ok(integrity)) = (temporary, domain, integrity) {\n"
    "            let store = FileGenerationStore::create_new(&temporary.path, domain, integrity);\n"
    "            assert!(store.is_ok());\n"
    "            if let Ok(mut store) = store {\n"
    "                let candidate = OpaqueState::new(b\"orphan-candidate\".to_vec());\n"
    "                assert!(candidate.is_ok());\n"
    "                if let Ok(candidate) = candidate {\n"
    "                    let intent = store.prepare_commit(None, &candidate);\n"
    "                    assert!(intent.is_ok());\n"
    "                    if let Ok(intent) = intent {\n"
    "                        let encoded = encode_bundle(\n"
    "                            intent.committed(),\n"
    "                            store.domain.as_str(),\n"
    "                            store.integrity.algorithm_id().as_str(),\n"
    "                            intent.digest(),\n"
    "                            candidate.as_bytes(),\n"
    "                        );\n"
    "                        assert!(encoded.is_ok());\n"
    "                        if let Ok(mut encoded) = encoded {\n"
    "                            let name = bundle_file_name(intent.committed());\n"
    "                            assert!(write_new_file_and_sync_parent(&store.root, &name, &encoded).is_ok());\n"
    "                            encoded.fill(0);\n"
    "                            assert_eq!(\n"
    "                                store.recover_commit(intent),\n"
    "                                Ok(CommitRecovery::Committed(intent.receipt()))\n"
    "                            );\n"
    "                            assert_eq!(store.current_generation(), Some(Generation::INITIAL));\n"
    "                        }\n"
    "                    }\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "    }\n\n"
    "    #[test]\n    fn compare_and_swap_rejects_stale_expected_generation() {\n",
)

# Journaled-core test store must satisfy the strengthened provider contract.
replace(
    "crates/heptabao-journaled-core/src/lib.rs",
    "    use heptabao_storage_api::{\n"
    "        GenerationSnapshot, OpaqueState, StateDigest, StorageContractError, StoreDomain,\n"
    "        StoreOpenMode,\n"
    "    };\n",
    "    use heptabao_storage_api::{\n"
    "        CommitIntent, CommitRecovery, GenerationSnapshot, OpaqueState, StateDigest,\n"
    "        StorageContractError, StoreDomain, StoreOpenMode,\n"
    "    };\n",
)
replace(
    "crates/heptabao-journaled-core/src/lib.rs",
    "        fn commit(\n"
    "            &mut self,\n"
    "            expected_current: Option<Generation>,\n"
    "            candidate: OpaqueState,\n"
    "        ) -> Result<CommitReceipt, Self::Error> {\n",
    "        fn prepare_commit(\n"
    "            &self,\n"
    "            expected_current: Option<Generation>,\n"
    "            candidate: &OpaqueState,\n"
    "        ) -> Result<CommitIntent, Self::Error> {\n"
    "            if expected_current != self.current {\n"
    "                return Err(MemoryStoreError::Conflict);\n"
    "            }\n"
    "            let committed = match self.current {\n"
    "                Some(value) => value.checked_next().map_err(MemoryStoreError::Contract)?,\n"
    "                None => Generation::INITIAL,\n"
    "            };\n"
    "            let digest = state_digest(committed, candidate.as_bytes())?;\n"
    "            CommitIntent::new(expected_current, committed, digest)\n"
    "                .map_err(MemoryStoreError::Contract)\n"
    "        }\n\n"
    "        fn recover_commit(\n"
    "            &mut self,\n"
    "            intent: CommitIntent,\n"
    "        ) -> Result<CommitRecovery, Self::Error> {\n"
    "            match (self.current, self.digest) {\n"
    "                (Some(generation), Some(digest))\n"
    "                    if generation == intent.committed() && digest == intent.digest() =>\n"
    "                {\n"
    "                    Ok(CommitRecovery::Committed(intent.receipt()))\n"
    "                }\n"
    "                (generation, _) if generation == intent.previous() => {\n"
    "                    Ok(CommitRecovery::NotCommitted)\n"
    "                }\n"
    "                (Some(generation), Some(digest)) => Ok(CommitRecovery::Conflict {\n"
    "                    actual: Some((generation, digest)),\n"
    "                }),\n"
    "                _ => Ok(CommitRecovery::Conflict { actual: None }),\n"
    "            }\n"
    "        }\n\n"
    "        fn commit(\n"
    "            &mut self,\n"
    "            expected_current: Option<Generation>,\n"
    "            candidate: OpaqueState,\n"
    "        ) -> Result<CommitReceipt, Self::Error> {\n",
)

print("V1.4.6 storage intent patch applied")
